In [46]:
import numpy as np 
import tensorflow as tf 

In [6]:
print(f"Tensorflow Version {tf.__version__}")

Tensorflow Version 2.20.0


In [9]:
hello = tf.constant("Hello Tensorflow")
print(hello.numpy().decode('utf-8'))

Hello Tensorflow


In [10]:
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [11]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
matrix = tf.constant([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [15]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
product = tf.matmul(matrix1, matrix2)
product.numpy()

array([[19, 22],
       [43, 50]], dtype=int32)

Creating variable in tf

In [17]:
changeable_tensor = tf.Variable([10, 20])
print(changeable_tensor.numpy())

[10 20]


In [18]:
changeable_tensor[0].assign(50)
print(changeable_tensor.numpy())

[50 20]


Creating Tensors with Specific Shapes

In [19]:
only_ones = tf.ones([2, 3])
print(only_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [20]:
only_zeros = tf.zeros([2, 2])
print(only_zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [21]:
# creating random tensors
random_tensor_normal_dist = tf.random.normal([2, 3])
print(random_tensor_normal_dist)

tf.Tensor(
[[ 0.3428715   0.70174956 -1.9512055 ]
 [-0.42327115  0.18916184 -1.5564494 ]], shape=(2, 3), dtype=float32)


In [22]:
random_tensor_uniform_dist = tf.random.uniform([2, 4])
print(random_tensor_uniform_dist)

tf.Tensor(
[[0.15740061 0.2324152  0.4969468  0.27572417]
 [0.33691216 0.32176518 0.3248179  0.68127954]], shape=(2, 4), dtype=float32)


In [24]:
rank_4_tensor = tf.zeros(shape=[2, 3, 2, 2])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor.dtype

tf.float32

In [26]:
rank_4_tensor.ndim

4

In [27]:
rank_4_tensor.shape

TensorShape([2, 3, 2, 2])

In [29]:
rank_4_tensor.shape[1]

3

In [ ]:
# Counts the total number of elements 
tf.size(rank_4_tensor).numpy()

np.int32(24)

Reshaping tensors

In [33]:
tensor = tf.constant([[10, 7], [3, 4]]) # (2, 2)
tensor.numpy()

array([[10,  7],
       [ 3,  4]], dtype=int32)

In [36]:
reshaped_tensor = tf.reshape(tensor, shape=[4, 1])
reshaped_tensor

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[10],
       [ 7],
       [ 3],
       [ 4]], dtype=int32)>

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])
print(new_tensor.shape)
new_tensor = tf.expand_dims(tensor, axis=0)
new_tensor

(1, 2, 2)


In [42]:
squeezable_tensor = tf.constant([[[1], [2], [3]]])
squeezable_tensor.shape

TensorShape([1, 3, 1])

In [43]:
squeezed_tensor = tf.squeeze(squeezable_tensor)
squeezed_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

One hot encoding

In [44]:
# Let's say: 0=Cat, 1=Dog, 2=Bird
indices = [0, 1, 2, 0]
depth = 3

one_hot_data = tf.one_hot(indices, depth)
one_hot_data

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)>

In [50]:
random_int_tensor = tf.constant(np.random.randint(0, 100, size=10))
random_int_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([90, 83, 59, 39, 11, 37, 29, 91, 41, 66], dtype=int32)>

In [51]:
tf.reduce_min(random_int_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [55]:
F = tf.constant(np.random.random(10))
F

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.6206912 , 0.00600682, 0.32473775, 0.98211739, 0.94577467,
       0.85780521, 0.87844023, 0.39189218, 0.12308901, 0.72087534])>

In [58]:
tf.argmax(F)
F[4].numpy()

np.float64(0.9457746675670218)

In [59]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>